version: "{build}"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

##os: Visual Studio 2019
#image:
#  - Visual Studio 2019
#  - Visual Studio 2017
#
#shallow_clone: true
#
#environment:
#  vs_root: C:\Program Files (x86)\Microsoft Visual Studio
#
#for:
#  -
#    matrix:
#      only:
#        - image: Visual Studio 2019
#    environment:
#      matrix:
#        # Visual Studio 2019 64bit
#        - visualcpp: $(vs_root)\2019\Community\VC\Auxiliary\Build\vcvars64.bat
#  -
#    matrix:
#      only:
#        - image: Visual Studio 2017
#    environment:
#      matrix:
#        # Visual Studio 2017 64bit
#        - visualcpp: $(vs_root)\2017\Community\VC\Auxiliary\Build\vcvars64.bat
#        # Visual Studio 2015 64bit
#        - visualcpp: $(vs_root) 14.0\VC\vcvarsall.bat
#          machine: amd64
#        # Visual Studio 2013 64bit
#        - visualcpp: $(vs_root) 12.0\VC\vcvarsall.bat
#          machine: amd64

init:
#  - call "%visualcpp%" %machine%
  - set PATH=C:\Ruby26-x64\bin;%PATH%

build_script:
  - ruby -v
#  - tzutil /l
  - tzutil /s "Romance Standard Time"
#  - rake -t time_zone
  - rake time_zone
  - bin\time_zone
