version: "{build}"

os: Visual Studio 2017

#image:
##  - Visual Studio 2019
#  - Visual Studio 2017
##  - Visual Studio 2015
##  - Visual Studio 2013

shallow_clone: true

environment:
  vs_root: C:\Program Files (x86)\Microsoft Visual Studio
  matrix:
    # Visual Studio 2017 64bit
    - visualcpp: $(vs_root)\2017\Community\VC\Auxiliary\Build\vcvars64.bat

#    # Visual Studio 2015 64bit
#    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
#      machine: amd64
#
#    # Visual Studio 2013 64bit
#    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
#      machine: amd64

#init:
#  - call "%visualcpp%" %machine%
#  # For using Rubyinstaller's Ruby 2.4 64bit
#  - set PATH=C:\Ruby24-x64\bin;%PATH%
#  - ruby --version
#
#install:
#  - if not exist win_flex_bison (
#      appveyor DownloadFile "https://github.com/lexxmark/winflexbison/releases/download/v.2.5.10/win_flex_bison-2.5.10.zip" &
#      7z x -y -owin_flex_bison win_flex_bison-2.5.10.zip
#    )

init:
  - call "%visualcpp%" %machine%
  - set PATH=C:\Ruby26-x64\bin;%PATH%

build_script:
  - ruby --version
#  - tzutil /l
  - tzutil /s "Romance Standard Time"
  - rake -t time_zone
