version: "{build}"

environment:
  vs_root: C:\Program Files (x86)\Microsoft Visual Studio
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      vc: $(vs_root)\2019\Community\VC\Auxiliary\Build\vcvars64.bat
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vc: $(vs_root)\2017\Community\VC\Auxiliary\Build\vcvars64.bat
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      vc: $(vs_root) 14.0\VC\vcvarsall.bat
      arch: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      vc: $(vs_root) 12.0\VC\vcvarsall.bat
      arch: amd64

init:
  - call "%vc%" %arch%
  - set PATH=C:\Ruby26-x64\bin;%PATH%

build_script:
#  - ruby -v
#  - rake -E $stdout.sync=true -s run_with_print
  - rake -E $stdout.sync=true
  - rake -E $stdout.sync=true CFLAGS=/TP  # C++
